-- AlterTable
ALTER TABLE "Pokemon" ADD COLUMN     "description" TEXT,
ADD COLUMN     "gender" TEXT,
ALTER COLUMN "height" DROP NOT NULL,
ALTER COLUMN "height" DROP DEFAULT,
ALTER COLUMN "height" SET DATA TYPE TEXT,
ALTER COLUMN "weight" DROP NOT NULL,
ALTER COLUMN "weight" DROP DEFAULT,
ALTER COLUMN "weight" SET DATA TYPE TEXT;
